### PR TITLE
Check the cast! Sometimes it isn't PlayerModel

### PR DESCRIPTION
**Pull request by itsmeow**

### CODE REVIEW

**Comment by MrCrayfish** [comment]
When is the player's model not a PlayerModel? It's redundant to check as I've already tested for the PlayerEntity instance.

**Comment by itsmeow** [comment]
When I do dumb things and change it to something else. The Morph mod would also probably break this.
[crash-2020-10-30_01.41.29-client.txt](https://github.com/MrCrayfish/Obfuscate/files/5463248/crash-2020-10-30_01.41.29-client.txt)

**Comment by Cheaterpaul** [comment]
if someone renders another model it is not the PlayerModel #23

**Comment by maxanier** [comment]
@MrCrayfish Any reason this is not merged yet? Even if you do not accept that this is a bug, it is a tiny change that does no harm at all.

**Comment by notWaterGuy12** [comment]
I'm really surprised that a fix was offered for this, and it's confirmed to be a bug for months now, and it still hasn't been implemented. Seems like such an effortless fix and yet it hasn't happened yet. Not to mention that it's a minor edit to a single line of code in the mod.

**Comment by SweetestBoy** [comment]
I see where you merged in updated it in the code for 1.16.5 but have yet to make a public release? Will one become available, if not how do you turn the code into a functioning .jar file?

**Pull request merged**
